name: Python EDA Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eda:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install TA-Lib
      run: |
        # Install precompiled TA-Lib wheel from the new repository
        pip install https://github.com/cgohlke/talib-build/releases/download/v0.4.32/TA_Lib-0.4.32-cp310-cp310-win_amd64.whl
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter  # Install Jupyter to run notebooks


    - name: Run EDA Script
      run: |

        jupyter nbconvert --to html --execute stock_market_data_analysis/notebooks/yfinance_analysis.ipynb
